## MC vs Split CP 시뮬레이션 — 여러 scenario 실행

설계 기준: 프로젝트 루트의 `시뮬.md`, 구현 지침: `CLAUDE.md`

`MC_CP_simulation.ipynb`에서 한 scenario를 따라가며 확인한 계산을, **맨 위 `SCENARIOS`에 넣은 scenario들에 대해 for문으로** 실행한다. 따라가기 셀(r=1, b=1)과 검증 셀은 넣지 않는다.

### MC_CP_simulation.ipynb와의 대응

| MC_CP_simulation.ipynb | 이 노트북 |
| --- | --- |
| 1~5절: imports, 설정, 난수, DGP, grid | 위쪽 설정 셀들 (같은 코드) |
| 7절 `fit_rf_oob` | 같은 함수 |
| 10절 `run_one_r` | 같은 함수 (고정값을 전역 변수 대신 인자로 받음) |
| 6절 training → 7절 기준 RF → 8절 CV → 진단 → 10절 r 반복·집계 → 11절 저장 | **메인 for문 셀 안에 같은 순서로** (블록마다 절 번호 주석) |
| (없음) | `[재개]` 표시 블록: 중간에 멈춘 뒤 이어서 계산하기 위한 코드 |

### 실행 모드

- `'smoke'` : 구조 검증용 작은 실행 (R=2, B=5, 트리 30개). **연구 결과가 아니다.** 결과는 `results/smoke/<scenario>/`
- `'full'` : 설계값 (R=200, B=200, 트리 1000개). 결과는 `results/<scenario>/`

In [1]:
# ===== 이번에 실행할 scenario: 여기에 돌리고 싶은 것만 넣는다 =====
# 가능한 이름: 'linear_homo_gaussian', 'linear_homo_student_t', 'nonlinear_homo_gaussian', 'nonlinear_homo_student_t'
SCENARIOS = [
    'linear_homo_gaussian',
    'linear_homo_student_t',
    'nonlinear_homo_gaussian',
    'nonlinear_homo_student_t',
]

# ===== 실행 모드: 'smoke' (구조 검증용 작은 실행) 또는 'full' (설계값) =====
RUN_MODE = 'smoke'

In [2]:
import json
import os
import platform
import sys
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import sklearn
from joblib import Parallel, delayed
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold

# 현재 위치에서 위로 올라가며 시뮬.md가 있는 폴더를 찾는다 → 프로젝트 루트
PROJECT_ROOT = None
here = Path.cwd().resolve()
for folder in [here] + list(here.parents):
    if (folder / '시뮬.md').exists():
        PROJECT_ROOT = folder
        break

if PROJECT_ROOT is None:
    raise FileNotFoundError('시뮬.md를 찾지 못했습니다. 프로젝트 폴더 안에서 노트북을 실행하세요.')

# OOB 예측이 없는 관측치가 생기면 경고 대신 오류로 멈춘다 (sklearn은 0으로 채우고 경고만 냄)
warnings.filterwarnings('error', message='Some inputs do not have OOB scores')
# RF를 n_jobs=-1로 병렬 학습할 때 나오는 안내성 경고 (결과와 무관) → 끈다
warnings.filterwarnings('ignore', message='`sklearn.utils.parallel.delayed` should be used')

print('PROJECT_ROOT :', PROJECT_ROOT)
print('python       :', sys.version.split()[0])
print('numpy        :', np.__version__)
print('pandas       :', pd.__version__)
print('scikit-learn :', sklearn.__version__)

PROJECT_ROOT : C:\Users\cho03\Desktop\조민석\연구
python       : 3.13.15
numpy        : 2.5.3
pandas       : 3.0.6
scikit-learn : 1.9.1

In [3]:
# ----- 확정 설계값 (시뮬.md) -----
N_TRAIN = 1000
N_CAL = 1000
GRID_AXIS = [-1.0, -0.5, 0.0, 0.5, 1.0]
ALPHAS = [0.10, 0.05]

# ----- 구현 기본값 (시뮬.md에 수치가 없어 정한 변경 가능한 제안값) -----
MASTER_SEED = 0
MC_QUANTILE_METHOD = 'linear'
CV_FOLDS = 10
MAX_DEPTH = None
# MC의 b를 동시에 몇 개 계산할지 (이 컴퓨터의 논리 코어 수). 결과에는 영향이 없고 속도만 바뀐다.
# 데이터가 1,000행으로 작아 RF 하나를 여러 스레드로 나누는 것보다 b 여러 개를 동시에 돌리는 것이 훨씬 빠르다
N_WORKERS = os.cpu_count()
# OOB grid search 후보 → 4 x 2 x 3 = 24개 조합
GRID_MIN_SAMPLES_LEAF = [5, 10, 20, 40]
GRID_MAX_FEATURES = [0.5, 1.0]
GRID_MAX_SAMPLES = [0.5, 0.7, 1.0]

# ----- 실행 모드별 규모 -----
if RUN_MODE == 'smoke':
    R = 2
    B = 5
    N_TREES = 30     # RF 하나 안의 결정트리 수
    RESULTS_DIR = PROJECT_ROOT / 'results' / 'smoke'
elif RUN_MODE == 'full':
    R = 200
    B = 200
    N_TREES = 1000
    RESULTS_DIR = PROJECT_ROOT / 'results'
else:
    raise ValueError("RUN_MODE는 'smoke' 또는 'full'")

print('RUN_MODE      :', RUN_MODE)
print('R, B, 트리 수 :', R, B, N_TREES)
print('SCENARIOS     :', SCENARIOS)
print('RESULTS_DIR   :', RESULTS_DIR)
print('N_WORKERS     :', N_WORKERS, '(MC의 b를 동시에 계산하는 수)')

RUN_MODE      : smoke
R, B, 트리 수 : 2 5 30
SCENARIOS     : ['linear_homo_gaussian', 'linear_homo_student_t', 'nonlinear_homo_gaussian', 'nonlinear_homo_student_t']
RESULTS_DIR   : C:\Users\cho03\Desktop\조민석\연구\results\smoke
N_WORKERS     : 32 (MC의 b를 동시에 계산하는 수)

In [4]:
# 난수 키 = [MASTER_SEED, scenario_id, stage_id, r, b, fold]
# r=1..R, b=1..B, fold=1..CV_FOLDS, 해당 단계에 필요 없는 인덱스는 0
# scenario_id는 고정이라 SCENARIOS에 일부만 넣거나 순서를 바꿔도 난수는 같다
SCENARIO_IDS = {
    'linear_homo_gaussian': 0,
    'linear_homo_student_t': 1,
    'nonlinear_homo_gaussian': 2,
    'nonlinear_homo_student_t': 3,
}
STAGE_IDS = {
    'common_dataset': 0,
    'common_training': 1,
    'cv_split': 2,
    'cv_model': 3,
    'cp_calibration': 4,
    'mc_dataset': 5,
    'mc_training': 6,
    'mc_new_error': 7,
    'test_error': 8,
}


def make_random_state(scenario, stage, r=0, b=0, fold=0):
    # 키 → SeedSequence → 정수 4개 → RandomState. 부를 때마다 새 객체를 만든다.
    key = [MASTER_SEED, SCENARIO_IDS[scenario], STAGE_IDS[stage], r, b, fold]
    words = np.random.SeedSequence(key).generate_state(4)
    return np.random.RandomState(words)


# SCENARIOS에 잘못된 이름이 있으면 여기서 멈춘다
for scenario in SCENARIOS:
    if scenario not in SCENARIO_IDS:
        raise ValueError(f'알 수 없는 scenario: {scenario}')
    print(scenario, '→ scenario_id', SCENARIO_IDS[scenario])

linear_homo_gaussian → scenario_id 0
linear_homo_student_t → scenario_id 1
nonlinear_homo_gaussian → scenario_id 2
nonlinear_homo_student_t → scenario_id 3

In [5]:
def mean_function(scenario, X):
    # 참평균 m(x). linear: x1 + x2, nonlinear: sqrt(2/3) sin(pi x1) + x2
    if scenario.startswith('linear'):
        return X[:, 0] + X[:, 1]
    elif scenario.startswith('nonlinear'):
        return np.sqrt(2 / 3) * np.sin(np.pi * X[:, 0]) + X[:, 1]
    else:
        raise ValueError(scenario)


def draw_error(scenario, random_seed, size):
    # 참오차 ε (평균 0, 분산 1). gaussian: N(0,1), student_t: t_3 / sqrt(3)
    if scenario.endswith('gaussian'):
        return random_seed.normal(size=size)
    elif scenario.endswith('student_t'):
        return random_seed.standard_t(3, size=size) / np.sqrt(3)
    else:
        raise ValueError(scenario)


# grid 25개: 바깥 루프 x1, 안쪽 루프 x2, grid_id 0~24로 고정
grid_points = []
for x1 in GRID_AXIS:
    for x2 in GRID_AXIS:
        grid_points.append([x1, x2])
X_grid = np.array(grid_points)
N_GRID = len(X_grid)

print('X_grid.shape :', X_grid.shape)

X_grid.shape : (25, 2)

In [6]:
def fit_rf_oob(X, y, scenario, stage, r=0, b=0, fold=0, n_jobs=-1):
    # Fit = OOB grid search + 학습. 선택된 RF, 선택 조합, 조합별 OOB MSE 표를 돌려준다.
    # n_jobs: RF 하나의 학습 스레드 수. 기준 RF는 -1(모든 코어), MC는 b를 동시에 돌리므로 1.
    #         RF 결과는 random_state로 정해지므로 n_jobs와 상관없이 같은 모델이 나온다.
    rows = []
    best_model = None
    best_mse = np.inf
    best_params = None

    for leaf in GRID_MIN_SAMPLES_LEAF:
        for feat in GRID_MAX_FEATURES:
            for samp in GRID_MAX_SAMPLES:
                rf = RandomForestRegressor(
                    n_estimators=N_TREES,
                    min_samples_leaf=leaf,
                    max_features=feat,
                    max_samples=samp,
                    max_depth=MAX_DEPTH,
                    bootstrap=True,
                    oob_score=True,
                    n_jobs=n_jobs,
                    random_state=make_random_state(scenario, stage, r=r, b=b, fold=fold),
                )
                rf.fit(X, y)

                oob_mse = np.mean((y - rf.oob_prediction_) ** 2)
                rows.append([leaf, feat, samp, oob_mse])

                if oob_mse < best_mse:   # 같으면 교체하지 않음 → 동률이면 grid 순서상 먼저
                    best_mse = oob_mse
                    best_model = rf
                    best_params = (leaf, feat, samp)

    # 예측은 단일 스레드로: n_jobs=-1로 예측하면 여러 스레드가 트리 예측을 더하는 순서가 실행마다 달라
    # 끝자리(1e-15 수준)가 흔들린다. 학습은 병렬 그대로, 예측만 n_jobs=1로 바꿔 같은 키 → 비트 단위로 같은 결과
    best_model.set_params(n_jobs=1)

    oob_table = pd.DataFrame(rows, columns=['min_samples_leaf', 'max_features', 'max_samples', 'oob_mse'])
    return best_model, best_params, oob_table

In [7]:
def run_one_b(scenario, r, b, best_train_pred, sigma_hat, X_train):
    # MC의 b 하나: 가상 Y* → OOB 튜닝 + 학습 → grid 25개 예측 + 새 오차 (9-3과 같은 계산)
    # 별도 프로세스에서 실행되므로 경고 설정을 여기서 다시 한다 (OOB 예측 누락 → 오류)
    warnings.filterwarnings('error', message='Some inputs do not have OOB scores')
    warnings.filterwarnings('ignore', message='`sklearn.utils.parallel.delayed` should be used')

    random_seed = make_random_state(scenario, "mc_dataset", r = r, b = b)
    mc_Y = best_train_pred + random_seed.normal(0, sigma_hat, N_TRAIN)

    mc_model, mc_params, mc_table = fit_rf_oob(X_train, mc_Y, scenario, "mc_training", r = r, b = b, n_jobs = 1)
    selection_row = [scenario, "mc", r, b, mc_params[0], mc_params[1], mc_params[2], mc_table["oob_mse"].min()]

    random_seed = make_random_state(scenario, "mc_new_error", r = r, b = b)
    mc_row = mc_model.predict(X_grid) + random_seed.normal(0, sigma_hat, N_GRID)
    return mc_row, selection_row


def run_one_r(scenario, r, best_model, best_train_pred, grid_predict, sigma_hat, X_train):
    # 한 번의 반복 r: 평가 Y → CP 구간 → MC 구간 → 채점. (MC_CP_simulation.ipynb 10절과 같은 함수)
    # 돌려주는 것: (채점 결과 100행 = grid 25 × alpha 2 × method 2, MC 선택 조합 B행)
    # 고정값(best_model, best_train_pred, grid_predict, sigma_hat, X_train)은 인자로 받는다.

    # 1. 평가 반응값 (9-1)
    random_seed = make_random_state(scenario, "test_error", r = r)
    true_mean = mean_function(scenario, X_grid)
    Y_test = true_mean + draw_error(scenario, random_seed, N_GRID)

    # 2. CP (9-2): 새 calibration → score → 순위 분위수
    random_seed = make_random_state(scenario, "cp_calibration", r = r)
    CP_X = random_seed.uniform(-1, 1, size=(N_CAL, 2))
    CP_Y = mean_function(scenario, CP_X) + draw_error(scenario, random_seed, N_CAL)
    s = sorted(np.abs(CP_Y - best_model.predict(CP_X)))

    cp_lower = {}
    cp_upper = {}
    for alpha in ALPHAS:
        k_alpha = np.ceil((N_CAL + 1) * (1 - alpha))
        if k_alpha > N_CAL:
            q_alpha = np.inf
        else:
            q_alpha = s[int(k_alpha) - 1]
        cp_lower[alpha] = grid_predict - q_alpha
        cp_upper[alpha] = grid_predict + q_alpha

    # 3. MC (9-3, 9-4): b = 1..B 가상 데이터 → OOB 튜닝 + 학습 → grid 예측 + 새 오차
    #    b = 1..B를 N_WORKERS개씩 동시에 계산한다. 결과는 b 순서대로 돌아오고, 난수 키가 b로 정해지므로
    #    순서대로 하나씩 계산한 것과 비트 단위로 같다.
    #    넘기는 배열이 작아(1,000행) 임시 파일 공유(memmap)는 끈다 (max_nbytes=None)
    b_results = Parallel(n_jobs=N_WORKERS, backend='loky', max_nbytes=None)(
        delayed(run_one_b)(scenario, r, b, best_train_pred, sigma_hat, X_train) for b in range(1, B + 1)
    )

    mc_samples = np.zeros((B, N_GRID))   # 행 = b, 열 = grid
    selection_rows = []                  # (r, b)마다 OOB 튜닝으로 선택된 조합 → model_selection.csv
    for b in range(1, B + 1):
        mc_row, selection_row = b_results[b - 1]
        mc_samples[b - 1] = mc_row
        selection_rows.append(selection_row)

    mc_lower = {}
    mc_upper = {}
    for alpha in ALPHAS:
        mc_lower[alpha] = np.quantile(mc_samples, alpha / 2, axis=0, method=MC_QUANTILE_METHOD)
        mc_upper[alpha] = np.quantile(mc_samples, 1 - alpha / 2, axis=0, method=MC_QUANTILE_METHOD)

    # 4. 채점 (9-5): 같은 Y_test로 두 방법·두 alpha
    tables = []
    for alpha in ALPHAS:
        for method in ["mc", "cp"]:
            if method == "mc":
                lower = mc_lower[alpha]
                upper = mc_upper[alpha]
            else:
                lower = cp_lower[alpha]
                upper = cp_upper[alpha]

            covered = (lower <= Y_test) & (Y_test <= upper)   # 25개 True/False (경계 포함)
            tables.append(pd.DataFrame({
                "scenario" : scenario,
                "r" : r,
                "grid_id" : np.arange(N_GRID),
                "x1" : X_grid[:, 0],
                "x2" : X_grid[:, 1],
                "alpha" : alpha,
                "method" : method,
                "y_true" : Y_test,
                "true_mean" : true_mean,
                "lower" : lower,
                "upper" : upper,
                "covered" : covered.astype(int),
                "length" : upper - lower,
            }))

    r_selection = pd.DataFrame(selection_rows, columns=[
        "scenario", "stage", "r", "b", "min_samples_leaf", "max_features", "max_samples", "oob_mse",
    ])
    return pd.concat(tables, ignore_index=True), r_selection

## 저장과 재개

```text
results/<mode>/<scenario>/
    config.json                 설정·σ̂²·난수 정책·라이브러리 버전·완료 r 목록 (r마다 갱신)
    r_results/
        selection_r001.csv      r = 1의 MC 선택 조합 B행
        interval_r001.csv       r = 1의 채점 결과 100행
        ...
    interval_metrics.csv, model_selection.csv, test_grid.csv, point_summary.csv, method_comparison.csv
```

- r 하나가 끝날 때마다 `r_results/`에 그 r의 결과를 저장한다. **두 파일이 모두 있으면 재개 대상 완료 r (집계 시 내용 검증)**이다.
- 다시 실행하면 `[재개]` 블록이 (1) 저장된 설정(`run_settings`)이 지금과 같은지, (2) 다시 계산한 기준 RF 조합과 $\widehat\sigma^2$가 저장값과 정확히 같은지 확인하고, (3) 완료된 r은 건너뛴다. 하나라도 다르면 오류로 멈추고 기존 결과는 지우지 않는다.
- **계산 코드를 바꾸면 `results/`의 기존 결과를 지우고 처음부터 다시 돌린다.** (재개 검사는 설정값만 비교하므로, 코드만 바뀐 경우는 잡지 못한다)
- **요약 파일은 R개 r이 모두 끝난 뒤에만 만든다.** 중간에 멈추면 r 파일과 config만 남고, 다시 실행하면 이어서 계산한 뒤 요약을 만든다.
- 파일은 임시 파일(`.tmp`)에 먼저 쓰고 이름을 바꾼다 → 쓰는 도중 멈춰도 반쯤 쓴 파일이 완료로 보이지 않는다.
- CSV는 `float_precision='round_trip'`으로 읽는다 → 저장한 실수를 비트 단위로 그대로 읽는다 (pandas 기본 읽기는 끝자리가 달라질 수 있음).

`r`은 1..R, `grid_id`는 0..24 (x1 바깥, x2 안쪽 순서), `method`는 `mc`/`cp`

In [8]:
def write_csv_atomic(df, path):
    # 임시 파일에 쓴 뒤 이름을 바꾼다
    tmp_path = path.with_name(path.name + '.tmp')
    df.to_csv(tmp_path, index=False)
    os.replace(tmp_path, path)


def write_json_atomic(obj, path):
    tmp_path = path.with_name(path.name + '.tmp')
    with open(tmp_path, 'w', encoding='utf-8') as file:
        # numpy 숫자(np.int64, np.float64)는 .item()으로 파이썬 숫자로 바꿔 저장
        json.dump(obj, file, ensure_ascii=False, indent=2, default=lambda value: value.item())
    os.replace(tmp_path, path)

In [9]:
def aggregate_saved_results(save_dir):
    # 학습 없이 저장된 r 파일을 읽어 요약을 만든다. 모든 r(R개)이 완료된 경우에만 집계한다 (미완료 요약은 만들지 않음).
    save_dir = Path(save_dir)
    config_path = save_dir / 'config.json'
    if not config_path.exists():
        print(f'{save_dir}: config.json 없음 → 건너뜀')
        return False
    with open(config_path, encoding='utf-8') as file:
        config = json.load(file)
    scenario = config['scenario']
    settings = config['run_settings']
    R, B = settings['R'], settings['B']
    ALPHAS = settings['alphas']
    N_GRID = len(settings['grid_axis']) ** 2
    params = config['base_rf']['best_params']
    best_params = (params['min_samples_leaf'], params['max_features'], params['max_samples'])
    oob_table = pd.DataFrame(config['base_rf']['oob_table'])
    r_dir = save_dir / 'r_results'
    completed_r = [r for r in range(1, R + 1)
                   if (r_dir / f'interval_r{r:03d}.csv').exists()
                   and (r_dir / f'selection_r{r:03d}.csv').exists()]
    if len(completed_r) != R:
        print(f'{scenario}: 완료 r {len(completed_r)} / {R} → 미완료라 요약을 만들지 않음')
        return False
    # ----- 10절. 집계: 저장된 r 파일을 모두 읽어 모은다 (메모리 값이 아니라 파일 기준) -----
    r_tables = []
    selection_tables = []
    for r in sorted(completed_r):
        r_result = pd.read_csv(r_dir / f'interval_r{r:03d}.csv', float_precision='round_trip')
        r_selection = pd.read_csv(r_dir / f'selection_r{r:03d}.csv', float_precision='round_trip')
        if len(r_result) != N_GRID * len(ALPHAS) * 2 or set(r_result['r']) != {r} or set(r_result['scenario']) != {scenario}:
            raise ValueError(f'interval_r{r:03d}.csv: 행 수 또는 r·scenario 값이 맞지 않음')
        if len(r_selection) != B or set(r_selection['r']) != {r} or set(r_selection['scenario']) != {scenario}:
            raise ValueError(f'selection_r{r:03d}.csv: 행 수 또는 r·scenario 값이 맞지 않음')
        expected_keys = {(i, a, h) for i in range(N_GRID) for a in ALPHAS for h in ['mc', 'cp']}
        actual_keys = set(r_result[['grid_id', 'alpha', 'method']].itertuples(index=False, name=None))
        if actual_keys != expected_keys:
            raise ValueError(f'r={r}: grid·alpha·method 구성 불일치')
        if set(r_selection['b']) != set(range(1, B + 1)) or set(r_selection['stage']) != {'mc'}:
            raise ValueError(f'r={r}: MC 선택 모델 번호 불일치')
        if not np.isfinite(r_result[['y_true', 'true_mean', 'lower', 'upper', 'length']].to_numpy()).all():
            raise ValueError(f'r={r}: 비유한 결과값 (현재 alpha·n_cal 설정은 유한 구간이어야 함)')
        if not r_result['covered'].isin([0, 1]).all():
            raise ValueError(f'r={r}: covered는 0 또는 1이어야 함')
        expected_covered = ((r_result['lower'] <= r_result['y_true']) &
                            (r_result['y_true'] <= r_result['upper'])).astype(int)
        if not np.array_equal(expected_covered, r_result['covered']):
            raise ValueError(f'r={r}: covered 불일치')
        if (r_result['upper'] < r_result['lower']).any() or not np.allclose(
                r_result['length'], r_result['upper'] - r_result['lower'], rtol=1e-12, atol=1e-12):
            raise ValueError(f'r={r}: 구간 길이 불일치')
        if (r_result.groupby('grid_id')['y_true'].nunique() != 1).any():
            raise ValueError(f'r={r}: 방법·alpha별 평가 Y 공유 불일치')
        r_tables.append(r_result)
        selection_tables.append(r_selection)

    interval_metrics = pd.concat(r_tables, ignore_index=True)

    # 같은 r·grid·alpha 안에서 mc, cp가 번갈아 나오도록 정렬 (alpha는 0.10 → 0.05)
    interval_metrics["method_order"] = interval_metrics["method"].map({"mc": 0, "cp": 1})
    interval_metrics = interval_metrics.sort_values(
        ["r", "grid_id", "alpha", "method_order"], ascending=[True, True, False, True]
    ).drop(columns="method_order").reset_index(drop=True)

    n_duplicated = interval_metrics.duplicated(['scenario', 'r', 'grid_id', 'alpha', 'method']).sum()
    if n_duplicated > 0:
        raise ValueError(f'interval_metrics key 중복 {n_duplicated}개')

    # grid마다 반복 방향(r)으로 평균 → conditional coverage와 평균 길이
    point_summary = interval_metrics.groupby(["scenario", "grid_id", "x1", "x2", "alpha", "method"], as_index=False).agg(
        n_covered = ("covered", "sum"),
        n_evaluated = ("covered", "count"),
        coverage = ("covered", "mean"),
        length_mean = ("length", "mean"),
        length_sd = ("length", "std"),
    )
    point_summary["method_order"] = point_summary["method"].map({"mc": 0, "cp": 1})
    point_summary = point_summary.sort_values(
        ["grid_id", "alpha", "method_order"], ascending=[True, False, True]
    ).drop(columns="method_order").reset_index(drop=True)

    # ----- 11절. 저장 -----
    # model_selection.csv : 기준 RF 1행 (r = b = 0) + MC 선택 조합
    base_selection = pd.DataFrame([[
        scenario, "base", 0, 0, best_params[0], best_params[1], best_params[2], oob_table["oob_mse"].min()
    ]], columns=["scenario", "stage", "r", "b", "min_samples_leaf", "max_features", "max_samples", "oob_mse"])
    model_selection = pd.concat([base_selection] + selection_tables, ignore_index=True)

    # method_comparison.csv : grid × alpha마다 MC·CP를 한 행에 나란히 놓고 CP − MC 차이 계산
    mc_part = point_summary[point_summary["method"] == "mc"]
    cp_part = point_summary[point_summary["method"] == "cp"]
    mc_part = mc_part[["scenario", "grid_id", "x1", "x2", "alpha", "coverage", "length_mean"]].rename(
        columns={"coverage": "mc_coverage", "length_mean": "mc_length_mean"})
    cp_part = cp_part[["scenario", "grid_id", "alpha", "coverage", "length_mean"]].rename(
        columns={"coverage": "cp_coverage", "length_mean": "cp_length_mean"})

    method_comparison = mc_part.merge(cp_part, on=["scenario", "grid_id", "alpha"])
    method_comparison["coverage_cp_minus_mc"] = method_comparison["cp_coverage"] - method_comparison["mc_coverage"]
    method_comparison["length_cp_minus_mc"] = method_comparison["cp_length_mean"] - method_comparison["mc_length_mean"]
    method_comparison = method_comparison[[
        "scenario", "grid_id", "x1", "x2", "alpha",
        "mc_coverage", "cp_coverage", "coverage_cp_minus_mc",
        "mc_length_mean", "cp_length_mean", "length_cp_minus_mc",
    ]]

    write_csv_atomic(interval_metrics, save_dir / "interval_metrics.csv")
    write_csv_atomic(model_selection, save_dir / "model_selection.csv")
    write_csv_atomic(point_summary, save_dir / "point_summary.csv")
    write_csv_atomic(method_comparison, save_dir / "method_comparison.csv")
    config['completed_r'] = sorted(completed_r)
    config['is_complete'] = len(completed_r) == R
    write_json_atomic(config, config_path)

    print(f'  저장: interval_metrics {len(interval_metrics)}행, model_selection {len(model_selection)}행, '
          f'point_summary {len(point_summary)}행, method_comparison {len(method_comparison)}행')
    return True

In [10]:
# [재개] 저장된 결과와 반드시 같아야 하는 설정
run_settings = {
    'run_mode': RUN_MODE,
    'R': R,
    'B': B,
    'n_trees': N_TREES,
    'n_train': N_TRAIN,
    'n_cal': N_CAL,
    'grid_axis': GRID_AXIS,
    'alphas': ALPHAS,
    'master_seed': MASTER_SEED,
    'scenario_ids': SCENARIO_IDS,
    'stage_ids': STAGE_IDS,
    'cv_folds': CV_FOLDS,
    'mc_quantile_method': MC_QUANTILE_METHOD,
    'max_depth': MAX_DEPTH,
    'grid_min_samples_leaf': GRID_MIN_SAMPLES_LEAF,
    'grid_max_features': GRID_MAX_FEATURES,
    'grid_max_samples': GRID_MAX_SAMPLES,
    'python': sys.version.split()[0],
    'numpy': np.__version__,
    'pandas': pd.__version__,
    'scikit-learn': sklearn.__version__,
}
run_settings = json.loads(json.dumps(run_settings))   # config.json에서 읽은 값과 같은 형태로 맞춘다 (비교용)
run_settings

{'run_mode': 'smoke',
 'R': 2,
 'B': 5,
 'n_trees': 30,
 'n_train': 1000,
 'n_cal': 1000,
 'grid_axis': [-1.0, -0.5, 0.0, 0.5, 1.0],
 'alphas': [0.1, 0.05],
 'master_seed': 0,
 'scenario_ids': {'linear_homo_gaussian': 0,
  'linear_homo_student_t': 1,
  'nonlinear_homo_gaussian': 2,
  'nonlinear_homo_student_t': 3},
 'stage_ids': {'common_dataset': 0,
  'common_training': 1,
  'cv_split': 2,
  'cv_model': 3,
  'cp_calibration': 4,
  'mc_dataset': 5,
  'mc_training': 6,
  'mc_new_error': 7,
  'test_error': 8},
 'cv_folds': 10,
 'mc_quantile_method': 'linear',
 'max_depth': None,
 'grid_min_samples_leaf': [5, 10, 20, 40],
 'grid_max_features': [0.5, 1.0],
 'grid_max_samples': [0.5, 0.7, 1.0],
 'python': '3.13.15',
 'numpy': '2.5.3',
 'pandas': '3.0.6',
 'scikit-learn': '1.9.1'}

## 실행 — scenario for문

`SCENARIOS`의 scenario를 차례로 실행한다. 블록마다 `MC_CP_simulation.ipynb`의 절 번호를 주석으로 달았다. `[재개]` 블록은 이어서 계산하기 위한 파일 관리 코드이므로 계산 흐름을 읽을 때는 건너뛰어도 된다.

In [11]:
total_start = time.time()

for scenario in SCENARIOS:
    print('=' * 70)
    print(f'{scenario}  ({RUN_MODE}, R={R}, B={B}, 트리 {N_TREES}개)')
    scenario_start = time.time()

    save_dir = RESULTS_DIR / scenario
    r_dir = save_dir / 'r_results'
    r_dir.mkdir(parents=True, exist_ok=True)
    config_path = save_dir / 'config.json'

    # ----- 6절. training 데이터 생성: 생성기 하나에서 X → 오차 순서로 -----
    random_seed = make_random_state(scenario, 'common_dataset')
    X_train = random_seed.uniform(-1, 1, size=(N_TRAIN, 2))
    eps_train = draw_error(scenario, random_seed, N_TRAIN)
    Y_train = mean_function(scenario, X_train) + eps_train

    # ----- 7절. 기준 RF: OOB grid search -----
    best_model, best_params, oob_table = fit_rf_oob(X_train, Y_train, scenario, 'common_training')
    print('  기준 RF 조합 (min_samples_leaf, max_features, max_samples) :', best_params)

    # ----- 8절. CV 잔차분산: best_params 고정, fold마다 RF 하나만 학습 -----
    leaf, feat, samp = best_params
    kfold = KFold(n_splits=CV_FOLDS, shuffle=True, random_state=make_random_state(scenario, 'cv_split'))

    oof_pred = np.full(N_TRAIN, np.nan)        # 각 관측치의 OOF 예측
    oof_count = np.zeros(N_TRAIN, dtype=int)   # 각 관측치가 몇 번 예측됐는지

    fold = 0
    for train_idx, valid_idx in kfold.split(X_train):
        fold += 1   # fold는 1부터
        fold_model = RandomForestRegressor(
            n_estimators=N_TREES,
            min_samples_leaf=leaf,
            max_features=feat,
            max_samples=samp,
            max_depth=MAX_DEPTH,
            bootstrap=True,
            n_jobs=-1,
            random_state=make_random_state(scenario, 'cv_model', fold=fold),
        )
        fold_model.fit(X_train[train_idx], Y_train[train_idx])
        fold_model.set_params(n_jobs=1)   # 예측은 단일 스레드 (합산 순서 고정 → 재현)
        oof_pred[valid_idx] = fold_model.predict(X_train[valid_idx])
        oof_count[valid_idx] += 1

    assert (oof_count == 1).all()   # 모든 관측치가 자기가 빠진 fold 모델로 정확히 한 번 예측됨

    cv_residual = Y_train - oof_pred
    # 전체 training에서 조합을 선택했으므로 선택 편향과 평균함수 추정오차가 포함될 수 있음
    # 영향의 크기는 확인하지 않았으며 순수 오차분산의 불편추정량으로 해석하지 않음
    sigma2_hat = np.mean(cv_residual ** 2)     # 제곱평균 (np.var 아님)
    if not np.isfinite(sigma2_hat):
        raise ValueError('sigma2_hat이 유한하지 않음')
    if sigma2_hat == 0:
        raise ValueError('sigma2_hat = 0 (퇴화)')
    sigma_hat = np.sqrt(sigma2_hat)

    sigma2_oob = np.mean((Y_train - best_model.oob_prediction_) ** 2)   # 진단용 (MC에는 안 씀)

    # ----- 진단과 고정 예측값: grid에서 기준 RF 예측 vs 참평균 -----
    grid_predict = best_model.predict(X_grid)        # CP 구간의 중심 f̂(x_i)
    best_train_pred = best_model.predict(X_train)    # MC 가상 반응값의 중심 f̂(X_train)
    grid_true_mean = mean_function(scenario, X_grid)
    grid_error = grid_predict - grid_true_mean
    grid_rmse = np.sqrt(np.mean(grid_error ** 2))
    grid_mae = np.mean(np.abs(grid_error))

    print(f'  sigma2_hat (CV, MC에 사용) : {sigma2_hat:.6f}   sigma_hat : {sigma_hat:.6f}')
    print(f'  sigma2_oob (진단용)        : {sigma2_oob:.6f}')
    print(f'  grid RMSE / MAE (f̂ vs m)   : {grid_rmse:.6f} / {grid_mae:.6f}')

    # ===== [재개] 이전 실행이 있으면 설정·기준 RF 조합·sigma2_hat이 같은지 확인 =====
    if config_path.exists():
        with open(config_path, encoding='utf-8') as file:
            saved_config = json.load(file)

        saved_settings = saved_config.get('run_settings')
        if saved_settings != run_settings:
            diffs = []
            if saved_settings is None:
                diffs.append('  저장된 config.json에 run_settings가 없음')
            else:
                for key in sorted(set(saved_settings) | set(run_settings)):
                    if saved_settings.get(key) != run_settings.get(key):
                        diffs.append(f'  {key}: 저장 = {saved_settings.get(key)}, 지금 = {run_settings.get(key)}')
            raise ValueError('저장된 설정과 지금 설정이 다름 → 이어서 계산하지 않음\n' + '\n'.join(diffs))

        saved_params = saved_config['base_rf']['best_params']
        saved_params = (saved_params['min_samples_leaf'], saved_params['max_features'], saved_params['max_samples'])
        if saved_params != best_params:
            raise ValueError(f'기준 RF 조합이 다름: 저장 = {saved_params}, 지금 = {best_params}')
        if saved_config['sigma2_hat'] != float(sigma2_hat):
            raise ValueError(f'sigma2_hat이 다름: 저장 = {saved_config["sigma2_hat"]}, 지금 = {sigma2_hat}')
        print('  [재개] 저장된 설정·기준 RF 조합·sigma2_hat 일치 → 완료된 r은 건너뜀')
    elif any(r_dir.iterdir()):
        raise ValueError(f'{r_dir}에 파일이 있는데 config.json이 없음 → 이어서 계산하지 않음')

    # ----- 11절. config.json: r 반복 전에 만들어 두고, r마다 완료 목록만 갱신 -----
    config = {}
    config['design_doc'] = '시뮬.md'
    config['scenario'] = scenario
    config['run_mode'] = RUN_MODE
    if RUN_MODE == 'smoke':
        config['note'] = 'smoke: 구조 검증용 작은 실행 (연구 결과 아님)'
    config['run_settings'] = run_settings

    # 확정 설계값 (시뮬.md)
    config['design'] = {
        'n_train': N_TRAIN,
        'n_cal': N_CAL,
        'grid_axis': GRID_AXIS,
        'n_grid': N_GRID,
        'alphas': ALPHAS,
        'R_full': 200,
        'B_full': 200,
        'variance_estimator': 'cv',
        'mc_error_family': 'gaussian',
    }
    # 이번 실행 규모 (smoke면 줄인 값)
    config['run_size'] = {'R': R, 'B': B, 'n_trees': N_TREES}
    # 구현 기본값 (변경 가능한 제안값)
    config['implementation_defaults'] = {
        'master_seed': MASTER_SEED,
        'cv_folds': CV_FOLDS,
        'mc_quantile_method': MC_QUANTILE_METHOD,
        'n_trees_full': 1000,
        'rf_fixed': {'max_depth': MAX_DEPTH, 'bootstrap': True, 'oob_score': True, 'predict_n_jobs': 1},
        'rf_train_n_jobs': '기준 RF·CV fold RF는 -1, MC 재학습 RF는 1 (b를 N_WORKERS개 동시에 계산). RF 결과는 n_jobs와 무관',
        'n_workers': N_WORKERS,
        'rf_param_grid': {
            'min_samples_leaf': GRID_MIN_SAMPLES_LEAF,
            'max_features': GRID_MAX_FEATURES,
            'max_samples': GRID_MAX_SAMPLES,
        },
        'selection_rule': 'OOB MSE = mean((y - oob_prediction_)^2) 최소, 동률이면 grid 순서상 먼저 나온 조합',
    }
    # 확정 방식 조합
    config['method_choice'] = {
        'base_rf_tuning': 'OOB',
        'sigma2_estimation': 'CV, 기준 RF 조합 고정 (fold 안에서 다시 튜닝하지 않음)',
        'mc_rf_tuning': 'OOB (가상 데이터마다 다시 튜닝)',
    }
    # 기준 RF와 분산 추정 결과 (CV fold RF도 best_params를 그대로 씀)
    config['base_rf'] = {
        'best_params': {
            'min_samples_leaf': best_params[0],
            'max_features': best_params[1],
            'max_samples': best_params[2],
        },
        'oob_table': oob_table.to_dict(orient='records'),
    }
    config['sigma2_hat'] = float(sigma2_hat)
    config['sigma2_oob_diagnostic'] = float(sigma2_oob)
    config['diagnostics'] = {
        'pooled_cv_rmse': float(sigma_hat),
        'grid_rmse_base_vs_true_mean': float(grid_rmse),
        'grid_mae_base_vs_true_mean': float(grid_mae),
    }
    # 난수 정책
    config['rng'] = {
        'master_seed': MASTER_SEED,
        'scenario_ids': SCENARIO_IDS,
        'stage_ids': STAGE_IDS,
        'key_order': ['MASTER_SEED', 'scenario_id', 'stage_id', 'r', 'b', 'fold'],
        'index_rules': 'r=1..R, b=1..B, fold=1..CV_FOLDS; 해당 단계에 필요 없는 인덱스는 0',
        'generator': 'np.random.RandomState(np.random.SeedSequence(key).generate_state(4)); 부를 때마다 새 객체',
    }
    config['index_ranges'] = 'r=1..R, grid_id=0..24 (x1 바깥 루프, x2 안쪽 루프), method=mc/cp'
    # 실행 환경
    config['library_versions'] = {
        'python': sys.version.split()[0],
        'numpy': np.__version__,
        'pandas': pd.__version__,
        'scikit-learn': sklearn.__version__,
    }
    config['machine'] = {
        'platform': platform.platform(),
        'processor': platform.processor(),
        'cpu_count': os.cpu_count(),
    }

    # [재개] 지금까지 완료된 r (두 파일이 모두 있는 r)
    completed_r = []
    for r in range(1, R + 1):
        if (r_dir / f'interval_r{r:03d}.csv').exists() and (r_dir / f'selection_r{r:03d}.csv').exists():
            completed_r.append(r)
    config['completed_r'] = completed_r
    config['is_complete'] = len(completed_r) == R
    write_json_atomic(config, config_path)
    print(f'  이미 완료된 r : {len(completed_r)} / {R}')

    # test_grid.csv : grid 25개의 좌표·참평균·기준 RF 예측
    test_grid = pd.DataFrame({
        "scenario" : scenario,
        "grid_id" : np.arange(N_GRID),
        "x1" : X_grid[:, 0],
        "x2" : X_grid[:, 1],
        "true_mean" : grid_true_mean,
        "base_prediction" : grid_predict,
    })

    write_csv_atomic(test_grid, save_dir / "test_grid.csv")

    # ----- 10절. r 반복 -----
    for r in range(1, R + 1):
        interval_path = r_dir / f'interval_r{r:03d}.csv'
        selection_path = r_dir / f'selection_r{r:03d}.csv'

        # [재개] 이미 완료된 r은 건너뛴다
        if r in completed_r:
            continue

        r_start = time.time()
        r_result, r_selection = run_one_r(scenario, r, best_model, best_train_pred, grid_predict, sigma_hat, X_train)

        # [재개] r 결과 저장 (selection → interval 순서) 후 완료 목록 갱신
        write_csv_atomic(r_selection, selection_path)
        write_csv_atomic(r_result, interval_path)
        completed_r.append(r)
        config['completed_r'] = sorted(completed_r)
        config['is_complete'] = len(completed_r) == R
        write_json_atomic(config, config_path)

        print(f'  r={r}/{R} 완료 ({time.time() - r_start:.1f}초)  완료 {len(completed_r)}/{R}')

    aggregate_saved_results(save_dir)
    print(f'  {scenario} 끝 ({time.time() - scenario_start:.1f}초)')

print('=' * 70)
print(f'전체 {time.time() - total_start:.1f}초')

======================================================================
linear_homo_gaussian  (smoke, R=2, B=5, 트리 30개)

  기준 RF 조합 (min_samples_leaf, max_features, max_samples) : (20, 0.5, 1.0)

  sigma2_hat (CV, MC에 사용) : 1.063796   sigma_hat : 1.031405
  sigma2_oob (진단용)        : 1.044270
  grid RMSE / MAE (f̂ vs m)   : 0.219538 / 0.164974
  이미 완료된 r : 0 / 2

  r=1/2 완료 (3.7초)  완료 1/2

  r=2/2 완료 (3.0초)  완료 2/2
  저장: interval_metrics 200행, model_selection 11행, point_summary 100행, method_comparison 50행
  linear_homo_gaussian 끝 (8.8초)
======================================================================
linear_homo_student_t  (smoke, R=2, B=5, 트리 30개)

  기준 RF 조합 (min_samples_leaf, max_features, max_samples) : (20, 1.0, 0.5)

  sigma2_hat (CV, MC에 사용) : 0.873701   sigma_hat : 0.934720
  sigma2_oob (진단용)        : 0.875260
  grid RMSE / MAE (f̂ vs m)   : 0.225739 / 0.178053
  이미 완료된 r : 0 / 2

  r=1/2 완료 (2.9초)  완료 1/2

  r=2/2 완료 (2.9초)  완료 2/2
  저장: interval_metrics 200행, model_selection 11행, point_summary 100행, method_comparison 50행
  linear_homo_student_t 끝 (7.9초)
======================================================================
nonlinear_homo_gaussian  (smoke, R=2, B=5, 트리 30개)

  기준 RF 조합 (min_samples_leaf, max_features, max_samples) : (20, 0.5, 1.0)

  sigma2_hat (CV, MC에 사용) : 1.017323   sigma_hat : 1.008624
  sigma2_oob (진단용)        : 1.017141
  grid RMSE / MAE (f̂ vs m)   : 0.299600 / 0.227370
  이미 완료된 r : 0 / 2

  r=1/2 완료 (2.9초)  완료 1/2

  r=2/2 완료 (3.0초)  완료 2/2
  저장: interval_metrics 200행, model_selection 11행, point_summary 100행, method_comparison 50행
  nonlinear_homo_gaussian 끝 (7.9초)
======================================================================
nonlinear_homo_student_t  (smoke, R=2, B=5, 트리 30개)

  기준 RF 조합 (min_samples_leaf, max_features, max_samples) : (5, 0.5, 0.5)

  sigma2_hat (CV, MC에 사용) : 1.880475   sigma_hat : 1.371304
  sigma2_oob (진단용)        : 1.869371
  grid RMSE / MAE (f̂ vs m)   : 0.286611 / 0.228356
  이미 완료된 r : 0 / 2

  r=1/2 완료 (2.8초)  완료 1/2

  r=2/2 완료 (1.2초)  완료 2/2
  저장: interval_metrics 200행, model_selection 11행, point_summary 100행, method_comparison 50행
  nonlinear_homo_student_t 끝 (6.1초)
======================================================================
전체 30.7초

## 저장 결과 확인

저장된 파일을 다시 읽어 scenario마다 행 수·key 중복·평가 Y 공유·길이·집계 count·완료 여부를 확인한다. 미완료 scenario는 `n_evaluated`가 완료된 r 수로 나온다.

In [12]:
check_rows = []
for scenario in SCENARIOS:
    save_dir = RESULTS_DIR / scenario
    if not (save_dir / 'point_summary.csv').exists():
        print(f'{scenario}: 요약 없음 → 건너뜀')
        continue
    metrics = pd.read_csv(save_dir / 'interval_metrics.csv', float_precision='round_trip')
    selection = pd.read_csv(save_dir / 'model_selection.csv', float_precision='round_trip')
    summary = pd.read_csv(save_dir / 'point_summary.csv', float_precision='round_trip')
    comparison = pd.read_csv(save_dir / 'method_comparison.csv', float_precision='round_trip')
    with open(save_dir / 'config.json', encoding='utf-8') as file:
        saved_config = json.load(file)

    n_done = len(saved_config['completed_r'])
    check_rows.append({
        'scenario': scenario,
        'completed_r': f"{n_done} / {R}",
        'is_complete': saved_config['is_complete'],
        'interval_metrics': len(metrics),                       # 완료 r x 100
        'model_selection': len(selection),                      # 1 + 완료 r x B
        'point_summary': len(summary),                          # 100
        'method_comparison': len(comparison),                   # 50
        'key_duplicated': metrics.duplicated(['scenario', 'r', 'grid_id', 'alpha', 'method']).sum(),   # 0
        'y_true_per_point': metrics.groupby(['r', 'grid_id'])['y_true'].nunique().max(),             # 1
        'length_error': (metrics['length'] - (metrics['upper'] - metrics['lower'])).abs().max(),      # 0 또는 1e-15 수준
        'n_evaluated': sorted(summary['n_evaluated'].unique().tolist()),                             # [완료 r 수]
    })

print(f'기대값: interval_metrics = 완료 r x 100, model_selection = 1 + 완료 r x {B}, point_summary = 100, method_comparison = 50,')
print('        key_duplicated = 0, y_true_per_point = 1, n_evaluated = [완료 r 수]')
pd.DataFrame(check_rows)

기대값: interval_metrics = 완료 r x 100, model_selection = 1 + 완료 r x 5, point_summary = 100, method_comparison = 50,
        key_duplicated = 0, y_true_per_point = 1, n_evaluated = [완료 r 수]

,scenario,completed_r,is_complete,interval_metrics,model_selection,point_summary,method_comparison,key_duplicated,y_true_per_point,length_error,n_evaluated
0,linear_homo_gaussian,2 / 2,True,200,11,100,50,0,1,0.0,[2]
1,linear_homo_student_t,2 / 2,True,200,11,100,50,0,1,0.0,[2]
2,nonlinear_homo_gaussian,2 / 2,True,200,11,100,50,0,1,0.0,[2]
3,nonlinear_homo_student_t,2 / 2,True,200,11,100,50,0,1,0.0,[2]

## 결과 표 — scenario별 입력별 coverage와 평균 길이

scenario마다 두 표를 보인다.

1. 입력별 요약: index = (`x` = `[x1, x2]`, alpha, method), coverage $\widehat c_{h,\alpha}(x_i)$와 평균 길이 $\overline\ell_{h,\alpha}(x_i)$
2. 방법 비교: index = (`x`, alpha), MC·CP의 coverage·평균 길이와 차이(CP − MC)

해석할 때는 목표 coverage(0.90, 0.95)와의 차이를 먼저 보고 길이를 함께 본다. 두 방법의 coverage가 서로 가깝다는 이유만으로 둘 다 정확하다고 판단하지 않는다. CP가 모든 $x$에서 목표 conditional coverage를 보장하는 것은 아니다.

**smoke(R=2) 결과는 coverage가 0, 0.5, 1 중 하나로만 나오는 구조 확인용이며 연구 결과가 아니다.**

여러 컴퓨터에서 나눠 실행한 경우, 각 컴퓨터의 `results/<scenario>/` 폴더를 한 곳에 모은 뒤 `SCENARIOS`에 모든 scenario를 적은 뒤, 메인 for문 셀은 건너뛰고 위쪽 설정 셀들과 아래 셀만 실행하면 된다.

In [13]:
for scenario in SCENARIOS:
    save_dir = RESULTS_DIR / scenario
    if not (save_dir / 'point_summary.csv').exists():
        print(f'{scenario}: 요약 없음 → 건너뜀')
        continue
    with open(save_dir / 'config.json', encoding='utf-8') as file:
        saved_config = json.load(file)
    summary = pd.read_csv(save_dir / 'point_summary.csv', float_precision='round_trip')
    comparison = pd.read_csv(save_dir / 'method_comparison.csv', float_precision='round_trip')

    # 표시용 입력 벡터 문자열 '[x1, x2]' (저장 파일은 수치 좌표와 grid_id를 그대로 유지)
    summary['x'] = '[' + summary['x1'].map('{:g}'.format) + ', ' + summary['x2'].map('{:g}'.format) + ']'
    comparison['x'] = '[' + comparison['x1'].map('{:g}'.format) + ', ' + comparison['x2'].map('{:g}'.format) + ']'

    print('=' * 70)
    print(f"{scenario}  ({saved_config['run_mode']}, 완료 r {len(saved_config['completed_r'])} / {saved_config['run_size']['R']}, "
          f"is_complete = {saved_config['is_complete']})")
    if saved_config['run_mode'] == 'smoke':
        print('smoke: 구조 확인용, 연구 결과 아님')

    print('\n[입력별 요약]')
    display(summary.set_index(['x', 'alpha', 'method'])[['n_covered', 'n_evaluated', 'coverage', 'length_mean', 'length_sd']])

    print('\n[방법 비교]')
    display(comparison.set_index(['x', 'alpha'])[[
        'mc_coverage', 'cp_coverage', 'coverage_cp_minus_mc',
        'mc_length_mean', 'cp_length_mean', 'length_cp_minus_mc',
    ]])

======================================================================
linear_homo_gaussian  (smoke, 완료 r 2 / 2, is_complete = True)
smoke: 구조 확인용, 연구 결과 아님

[입력별 요약]

                         n_covered  n_evaluated  coverage  length_mean  \
x          alpha method
[-1, -1]   0.10  mc              2            2       1.0     2.574398
                 cp              2            2       1.0     3.410525
           0.05  mc              2            2       1.0     2.769495
                 cp              2            2       1.0     3.953448
[-1, -0.5] 0.10  mc              2            2       1.0     2.636209
...                            ...          ...       ...          ...
[1, 0.5]   0.05  cp              2            2       1.0     3.953448
[1, 1]     0.10  mc              0            2       0.0     0.774316
                 cp              2            2       1.0     3.410525
           0.05  mc              0            2       0.0     0.824649
                 cp              2            2       1.0     3.953448

                         length_sd
x          alpha method
[-1, -1]   0.10  mc       0.911895
                 cp       0.029763
           0.05  mc       1.129243
                 cp       0.132441
[-1, -0.5] 0.10  mc       0.217328
...                            ...
[1, 0.5]   0.05  cp       0.132441
[1, 1]     0.10  mc       0.008171
                 cp       0.029763
           0.05  mc       0.021381
                 cp       0.132441

[100 rows x 5 columns]

[방법 비교]

                    mc_coverage  cp_coverage  coverage_cp_minus_mc  \
x            alpha
[-1, -1]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-1, -0.5]   0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-1, 0]      0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[-1, 0.5]    0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[-1, 1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, -1]   0.10           0.0          0.5                   0.5
             0.05           0.0          1.0                   1.0
[-0.5, -0.5] 0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 0]    0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[-0.5, 0.5]  0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 1]    0.10           0.0          1.0                   1.0
             0.05           0.0          1.0                   1.0
[0, -1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, -0.5]    0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[0, 0]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, 0.5]     0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[0, 1]       0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[0.5, -1]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, -0.5]  0.10           0.0          1.0                   1.0
             0.05           0.0          1.0                   1.0
[0.5, 0]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, 0.5]   0.10           0.5          1.0                   0.5
             0.05           1.0          1.0                   0.0
[0.5, 1]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, -1]      0.10           1.0          0.5                  -0.5
             0.05           1.0          0.5                  -0.5
[1, -0.5]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, 0]       0.10           0.0          1.0                   1.0
             0.05           0.0          1.0                   1.0
[1, 0.5]     0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[1, 1]       0.10           0.0          1.0                   1.0
             0.05           0.0          1.0                   1.0

                    mc_length_mean  cp_length_mean  length_cp_minus_mc
x            alpha
[-1, -1]     0.10         2.574398        3.410525            0.836127
             0.05         2.769495        3.953448            1.183954
[-1, -0.5]   0.10         2.636209        3.410525            0.774316
             0.05         2.845414        3.953448            1.108034
[-1, 0]      0.10         1.490312        3.410525            1.920213
             0.05         1.621500        3.953448            2.331948
[-1, 0.5]    0.10         3.134133        3.410525            0.276392
             0.05         3.298424        3.953448            0.655024
[-1, 1]      0.10         1.427939        3.410525            1.982587
             0.05         1.492966        3.953448            2.460482
[-0.5, -1]   0.10         2.562689        3.410525            0.847837
             0.05         2.672648        3.953448            1.280800
[-0.5, -0.5] 0.10         2.523123        3.410525            0.887402
             0.05         2.651858        3.953448            1.301590
[-0.5, 0]    0.10         1.745426        3.410525            1.665099
             0.05         1.835793        3.953448            2.117655
[-0.5, 0.5]  0.10         2.526756        3.410525            0.883770
             0.05         2.694225        3.953448            1.259224
[-0.5, 1]    0.10         1.512776        3.410525            1.897750
             0.05         1.644375        3.953448            2.309073
[0, -1]      0.10         2.351385        3.410525            1.059141
             0.05         2.520862        3.953448            1.432586
[0, -0.5]    0.10         2.674547        3.410525            0.735979
             0.05         2.791045        3.953448            1.162403
[0, 0]       0.10         2.233042        3.410525            1.177484
             0.05         2.300138        3.953448            1.653310
[0, 0.5]     0.10         1.898317        3.410525            1.512209
             0.05         2.019039        3.953448            1.934409
[0, 1]       0.10         2.365143        3.410525            1.045383
             0.05         2.514669        3.953448            1.438779
[0.5, -1]    0.10         3.275141        3.410525            0.135384
             0.05         3.462155        3.953448            0.491293
[0.5, -0.5]  0.10         2.140930        3.410525            1.269595
             0.05         2.306481        3.953448            1.646967
[0.5, 0]     0.10         2.012463        3.410525            1.398062
             0.05         2.180248        3.953448            1.773200
[0.5, 0.5]   0.10         3.398520        3.410525            0.012005
             0.05         3.530292        3.953448            0.423156
[0.5, 1]     0.10         1.188504        3.410525            2.222021
             0.05         1.263254        3.953448            2.690194
[1, -1]      0.10         2.681642        3.410525            0.728884
             0.05         2.931459        3.953448            1.021989
[1, -0.5]    0.10         1.982837        3.410525            1.427689
             0.05         2.086072        3.953448            1.867376
[1, 0]       0.10         1.945643        3.410525            1.464883
             0.05         2.135871        3.953448            1.817577
[1, 0.5]     0.10         2.579648        3.410525            0.830878
             0.05         2.702874        3.953448            1.250574
[1, 1]       0.10         0.774316        3.410525            2.636209
             0.05         0.824649        3.953448            3.128799

======================================================================
linear_homo_student_t  (smoke, 완료 r 2 / 2, is_complete = True)
smoke: 구조 확인용, 연구 결과 아님

[입력별 요약]

                         n_covered  n_evaluated  coverage  length_mean  \
x          alpha method
[-1, -1]   0.10  mc              1            2       0.5     2.005616
                 cp              1            2       0.5     2.721837
           0.05  mc              1            2       0.5     2.126392
                 cp              2            2       1.0     3.651869
[-1, -0.5] 0.10  mc              1            2       0.5     2.267830
...                            ...          ...       ...          ...
[1, 0.5]   0.05  cp              2            2       1.0     3.651869
[1, 1]     0.10  mc              0            2       0.0     1.017441
                 cp              1            2       0.5     2.721837
           0.05  mc              0            2       0.0     1.129585
                 cp              2            2       1.0     3.651869

                         length_sd
x          alpha method
[-1, -1]   0.10  mc       0.304875
                 cp       0.092688
           0.05  mc       0.305594
                 cp       0.055701
[-1, -0.5] 0.10  mc       0.977370
...                            ...
[1, 0.5]   0.05  cp       0.055701
[1, 1]     0.10  mc       0.669454
                 cp       0.092688
           0.05  mc       0.745392
                 cp       0.055701

[100 rows x 5 columns]

[방법 비교]

                    mc_coverage  cp_coverage  coverage_cp_minus_mc  \
x            alpha
[-1, -1]     0.10           0.5          0.5                   0.0
             0.05           0.5          1.0                   0.5
[-1, -0.5]   0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[-1, 0]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-1, 0.5]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-1, 1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, -1]   0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, -0.5] 0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 0]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 0.5]  0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 1]    0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[0, -1]      0.10           0.0          0.5                   0.5
             0.05           0.0          1.0                   1.0
[0, -0.5]    0.10           0.5          0.5                   0.0
             0.05           0.5          1.0                   0.5
[0, 0]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, 0.5]     0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[0, 1]       0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[0.5, -1]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, -0.5]  0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, 0]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, 0.5]   0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, 1]     0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[1, -1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, -0.5]    0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[1, 0]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, 0.5]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, 1]       0.10           0.0          0.5                   0.5
             0.05           0.0          1.0                   1.0

                    mc_length_mean  cp_length_mean  length_cp_minus_mc
x            alpha
[-1, -1]     0.10         2.005616        2.721837            0.716221
             0.05         2.126392        3.651869            1.525477
[-1, -0.5]   0.10         2.267830        2.721837            0.454006
             0.05         2.347705        3.651869            1.304164
[-1, 0]      0.10         2.485483        2.721837            0.236354
             0.05         2.673899        3.651869            0.977970
[-1, 0.5]    0.10         2.326360        2.721837            0.395477
             0.05         2.532769        3.651869            1.119100
[-1, 1]      0.10         1.886876        2.721837            0.834960
             0.05         1.985573        3.651869            1.666296
[-0.5, -1]   0.10         2.838039        2.721837           -0.116202
             0.05         2.925799        3.651869            0.726070
[-0.5, -0.5] 0.10         1.820906        2.721837            0.900930
             0.05         1.942726        3.651869            1.709143
[-0.5, 0]    0.10         2.732962        2.721837           -0.011125
             0.05         2.914041        3.651869            0.737828
[-0.5, 0.5]  0.10         2.077896        2.721837            0.643941
             0.05         2.165986        3.651869            1.485883
[-0.5, 1]    0.10         1.995368        2.721837            0.726468
             0.05         2.188822        3.651869            1.463047
[0, -1]      0.10         1.181156        2.721837            1.540681
             0.05         1.264126        3.651869            2.387743
[0, -0.5]    0.10         1.607656        2.721837            1.114181
             0.05         1.697965        3.651869            1.953904
[0, 0]       0.10         1.635956        2.721837            1.085880
             0.05         1.720215        3.651869            1.931654
[0, 0.5]     0.10         1.911609        2.721837            0.810228
             0.05         1.989353        3.651869            1.662516
[0, 1]       0.10         1.827386        2.721837            0.894451
             0.05         1.884199        3.651869            1.767670
[0.5, -1]    0.10         2.221518        2.721837            0.500318
             0.05         2.343964        3.651869            1.307905
[0.5, -0.5]  0.10         1.858509        2.721837            0.863328
             0.05         1.981633        3.651869            1.670236
[0.5, 0]     0.10         1.668908        2.721837            1.052929
             0.05         1.821311        3.651869            1.830558
[0.5, 0.5]   0.10         1.913102        2.721837            0.808735
             0.05         2.051485        3.651869            1.600384
[0.5, 1]     0.10         1.900619        2.721837            0.821218
             0.05         2.042718        3.651869            1.609151
[1, -1]      0.10         1.792229        2.721837            0.929608
             0.05         1.943068        3.651869            1.708801
[1, -0.5]    0.10         1.700739        2.721837            1.021097
             0.05         1.832766        3.651869            1.819103
[1, 0]       0.10         1.878802        2.721837            0.843035
             0.05         1.967098        3.651869            1.684771
[1, 0.5]     0.10         2.499886        2.721837            0.221951
             0.05         2.744126        3.651869            0.907743
[1, 1]       0.10         1.017441        2.721837            1.704396
             0.05         1.129585        3.651869            2.522284

======================================================================
nonlinear_homo_gaussian  (smoke, 완료 r 2 / 2, is_complete = True)
smoke: 구조 확인용, 연구 결과 아님

[입력별 요약]

                         n_covered  n_evaluated  coverage  length_mean  \
x          alpha method
[-1, -1]   0.10  mc              1            2       0.5     2.480469
                 cp              1            2       0.5     3.409142
           0.05  mc              1            2       0.5     2.656565
                 cp              2            2       1.0     4.006628
[-1, -0.5] 0.10  mc              0            2       0.0     2.110926
...                            ...          ...       ...          ...
[1, 0.5]   0.05  cp              2            2       1.0     4.006628
[1, 1]     0.10  mc              2            2       1.0     1.604085
                 cp              2            2       1.0     3.409142
           0.05  mc              2            2       1.0     1.643433
                 cp              2            2       1.0     4.006628

                         length_sd
x          alpha method
[-1, -1]   0.10  mc       0.849187
                 cp       0.168382
           0.05  mc       1.011795
                 cp       0.076539
[-1, -0.5] 0.10  mc       0.070264
...                            ...
[1, 0.5]   0.05  cp       0.076539
[1, 1]     0.10  mc       0.617193
                 cp       0.168382
           0.05  mc       0.620648
                 cp       0.076539

[100 rows x 5 columns]

[방법 비교]

                    mc_coverage  cp_coverage  coverage_cp_minus_mc  \
x            alpha
[-1, -1]     0.10           0.5          0.5                   0.0
             0.05           0.5          1.0                   0.5
[-1, -0.5]   0.10           0.0          1.0                   1.0
             0.05           0.5          1.0                   0.5
[-1, 0]      0.10           0.0          0.5                   0.5
             0.05           0.0          0.5                   0.5
[-1, 0.5]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-1, 1]      0.10           0.5          1.0                   0.5
             0.05           1.0          1.0                   0.0
[-0.5, -1]   0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[-0.5, -0.5] 0.10           0.0          1.0                   1.0
             0.05           0.0          1.0                   1.0
[-0.5, 0]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 0.5]  0.10           0.0          0.0                   0.0
             0.05           0.0          0.5                   0.5
[-0.5, 1]    0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[0, -1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, -0.5]    0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[0, 0]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, 0.5]     0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[0, 1]       0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[0.5, -1]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, -0.5]  0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[0.5, 0]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, 0.5]   0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[0.5, 1]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, -1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, -0.5]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, 0]       0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[1, 0.5]     0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[1, 1]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0

                    mc_length_mean  cp_length_mean  length_cp_minus_mc
x            alpha
[-1, -1]     0.10         2.480469        3.409142            0.928673
             0.05         2.656565        4.006628            1.350063
[-1, -0.5]   0.10         2.110926        3.409142            1.298216
             0.05         2.275951        4.006628            1.730677
[-1, 0]      0.10         1.641772        3.409142            1.767370
             0.05         1.782235        4.006628            2.224393
[-1, 0.5]    0.10         2.366643        3.409142            1.042499
             0.05         2.494527        4.006628            1.512101
[-1, 1]      0.10         2.659686        3.409142            0.749456
             0.05         2.924004        4.006628            1.082624
[-0.5, -1]   0.10         1.051338        3.409142            2.357804
             0.05         1.145057        4.006628            2.861570
[-0.5, -0.5] 0.10         2.237305        3.409142            1.171837
             0.05         2.374236        4.006628            1.632392
[-0.5, 0]    0.10         2.080717        3.409142            1.328425
             0.05         2.118642        4.006628            1.887986
[-0.5, 0.5]  0.10         1.622334        3.409142            1.786808
             0.05         1.707534        4.006628            2.299094
[-0.5, 1]    0.10         2.003024        3.409142            1.406117
             0.05         2.186831        4.006628            1.819796
[0, -1]      0.10         1.375033        3.409142            2.034109
             0.05         1.485296        4.006628            2.521332
[0, -0.5]    0.10         2.276137        3.409142            1.133005
             0.05         2.402321        4.006628            1.604307
[0, 0]       0.10         1.787460        3.409142            1.621681
             0.05         1.928145        4.006628            2.078483
[0, 0.5]     0.10         1.764557        3.409142            1.644584
             0.05         1.880669        4.006628            2.125959
[0, 1]       0.10         1.506244        3.409142            1.902898
             0.05         1.598414        4.006628            2.408213
[0.5, -1]    0.10         2.491270        3.409142            0.917871
             0.05         2.629551        4.006628            1.377077
[0.5, -0.5]  0.10         2.083116        3.409142            1.326026
             0.05         2.270720        4.006628            1.735908
[0.5, 0]     0.10         2.604138        3.409142            0.805004
             0.05         2.743079        4.006628            1.263549
[0.5, 0.5]   0.10         2.619977        3.409142            0.789165
             0.05         2.820644        4.006628            1.185984
[0.5, 1]     0.10         1.670788        3.409142            1.738354
             0.05         1.758964        4.006628            2.247664
[1, -1]      0.10         2.114587        3.409142            1.294555
             0.05         2.285966        4.006628            1.720662
[1, -0.5]    0.10         2.781501        3.409142            0.627641
             0.05         2.957641        4.006628            1.048987
[1, 0]       0.10         1.707687        3.409142            1.701454
             0.05         1.815196        4.006628            2.191431
[1, 0.5]     0.10         2.235013        3.409142            1.174129
             0.05         2.319049        4.006628            1.687579
[1, 1]       0.10         1.604085        3.409142            1.805057
             0.05         1.643433        4.006628            2.363195

======================================================================
nonlinear_homo_student_t  (smoke, 완료 r 2 / 2, is_complete = True)
smoke: 구조 확인용, 연구 결과 아님

[입력별 요약]

                         n_covered  n_evaluated  coverage  length_mean  \
x          alpha method
[-1, -1]   0.10  mc              2            2       1.0     3.731868
                 cp              2            2       1.0     2.972881
           0.05  mc              2            2       1.0     4.040369
                 cp              2            2       1.0     3.904541
[-1, -0.5] 0.10  mc              2            2       1.0     2.654971
...                            ...          ...       ...          ...
[1, 0.5]   0.05  cp              1            2       0.5     3.904541
[1, 1]     0.10  mc              1            2       0.5     2.071557
                 cp              2            2       1.0     2.972881
           0.05  mc              1            2       0.5     2.173370
                 cp              2            2       1.0     3.904541

                         length_sd
x          alpha method
[-1, -1]   0.10  mc       0.123186
                 cp       0.132782
           0.05  mc       0.021203
                 cp       0.038501
[-1, -0.5] 0.10  mc       1.904281
...                            ...
[1, 0.5]   0.05  cp       0.038501
[1, 1]     0.10  mc       0.294788
                 cp       0.132782
           0.05  mc       0.344693
                 cp       0.038501

[100 rows x 5 columns]

[방법 비교]

                    mc_coverage  cp_coverage  coverage_cp_minus_mc  \
x            alpha
[-1, -1]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-1, -0.5]   0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-1, 0]      0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[-1, 0.5]    0.10           0.5          0.5                   0.0
             0.05           0.5          1.0                   0.5
[-1, 1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, -1]   0.10           0.5          0.5                   0.0
             0.05           0.5          1.0                   0.5
[-0.5, -0.5] 0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 0]    0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[-0.5, 0.5]  0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[-0.5, 1]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, -1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, -0.5]    0.10           0.5          1.0                   0.5
             0.05           1.0          1.0                   0.0
[0, 0]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, 0.5]     0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0, 1]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, -1]    0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5
[0.5, -0.5]  0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[0.5, 0]     0.10           0.0          0.5                   0.5
             0.05           0.0          0.5                   0.5
[0.5, 0.5]   0.10           0.0          1.0                   1.0
             0.05           0.0          1.0                   1.0
[0.5, 1]     0.10           0.0          1.0                   1.0
             0.05           0.0          1.0                   1.0
[1, -1]      0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, -0.5]    0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, 0]       0.10           1.0          1.0                   0.0
             0.05           1.0          1.0                   0.0
[1, 0.5]     0.10           0.5          0.5                   0.0
             0.05           0.5          0.5                   0.0
[1, 1]       0.10           0.5          1.0                   0.5
             0.05           0.5          1.0                   0.5

                    mc_length_mean  cp_length_mean  length_cp_minus_mc
x            alpha
[-1, -1]     0.10         3.731868        2.972881           -0.758987
             0.05         4.040369        3.904541           -0.135829
[-1, -0.5]   0.10         2.654971        2.972881            0.317910
             0.05         2.884115        3.904541            1.020425
[-1, 0]      0.10         1.432984        2.972881            1.539897
             0.05         1.533893        3.904541            2.370648
[-1, 0.5]    0.10         4.691258        2.972881           -1.718377
             0.05         4.903186        3.904541           -0.998646
[-1, 1]      0.10         3.710543        2.972881           -0.737662
             0.05         4.079544        3.904541           -0.175003
[-0.5, -1]   0.10         1.738109        2.972881            1.234772
             0.05         1.793412        3.904541            2.111129
[-0.5, -0.5] 0.10         2.613388        2.972881            0.359493
             0.05         2.860511        3.904541            1.044030
[-0.5, 0]    0.10         2.384067        2.972881            0.588814
             0.05         2.558210        3.904541            1.346331
[-0.5, 0.5]  0.10         4.298170        2.972881           -1.325289
             0.05         4.586761        3.904541           -0.682220
[-0.5, 1]    0.10         2.145476        2.972881            0.827405
             0.05         2.283382        3.904541            1.621159
[0, -1]      0.10         3.106768        2.972881           -0.133887
             0.05         3.430170        3.904541            0.474370
[0, -0.5]    0.10         1.822232        2.972881            1.150650
             0.05         1.899571        3.904541            2.004970
[0, 0]       0.10         3.529939        2.972881           -0.557058
             0.05         3.793427        3.904541            0.111114
[0, 0.5]     0.10         3.625892        2.972881           -0.653011
             0.05         3.734631        3.904541            0.169910
[0, 1]       0.10         3.108987        2.972881           -0.136106
             0.05         3.271206        3.904541            0.633335
[0.5, -1]    0.10         2.390305        2.972881            0.582576
             0.05         2.507858        3.904541            1.396683
[0.5, -0.5]  0.10         2.636134        2.972881            0.336747
             0.05         2.798217        3.904541            1.106324
[0.5, 0]     0.10         2.047863        2.972881            0.925018
             0.05         2.160585        3.904541            1.743956
[0.5, 0.5]   0.10         2.964028        2.972881            0.008853
             0.05         3.215310        3.904541            0.689231
[0.5, 1]     0.10         1.509436        2.972881            1.463445
             0.05         1.620415        3.904541            2.284126
[1, -1]      0.10         2.086066        2.972881            0.886815
             0.05         2.300467        3.904541            1.604074
[1, -0.5]    0.10         5.372919        2.972881           -2.400037
             0.05         5.736365        3.904541           -1.831825
[1, 0]       0.10         1.525690        2.972881            1.447191
             0.05         1.613445        3.904541            2.291096
[1, 0.5]     0.10         4.901930        2.972881           -1.929049
             0.05         5.137464        3.904541           -1.232923
[1, 1]       0.10         2.071557        2.972881            0.901324
             0.05         2.173370        3.904541            1.731171